### ISSUE TITLE
Small mobile optimization

### ISSUE THREAD

**Issue by Aristotle-P** [PickleBanquet/splurty#1]
On mobile things don't look as good as they could be. One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on mobile.

You can add it on the line I've referenced below.
https://github.com/PickleBanquet/splurty/blob/0ecefbed353bb1ea1cf1627c6d366869b34c6ee7/app/views/layouts/application.html.erb#L7

**Comment by PickleBanquet** [comment]
Thank you for the input.  I have added the tag and tested it out on mobile and it looks great!
